### ISSUE TITLE
Quetion for installation in MongoDB

### ISSUE THREAD

**Issue by jinxsfe** [kirchhausenlab/incasem#20]
![image](https://github.com/kirchhausenlab/incasem/assets/121477741/f0a84492-5d5d-4f37-bb50-a2b581b41bf9)
I had installed and based on the instruction for the online documentation, and the mingod service can run actively, but
![image](https://github.com/kirchhausenlab/incasem/assets/121477741/4b18dc02-43e5-4078-9852-45615146ef67)
I check the web it seems no need to run "bash sudo service mongod start" isn't it? what is different between systemd and service, does any bad effect for later process?

**Comment by jinxsfe** [comment]
![image](https://github.com/kirchhausenlab/incasem/assets/121477741/f0f59e00-be00-4404-a116-f601c845aba9)
when I downloaded , I also could not find the model installed.

**Comment by jinxsfe** [comment]
![image](https://github.com/kirchhausenlab/incasem/assets/121477741/dd2ebece-76d2-4845-93bb-39100c629421)
When I download, I also could not find the location for model 1481, it seems not exist pretrained model

**Comment by jinxsfe** [comment]
(incasem) js22bp@js22bp-MS-7D98:~/incasem/data$ neuroglancer -f cell_6/cell_6.zarr -d volumes/raw_equalized_0.02 volumes/labels/er volumes/predictions/er/segmentatio
/home/js22bp/miniconda3/envs/incasem/bin/neuroglancer:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('funlib.show.neuroglancer==0.1')
Adding cell_6/cell_6.zarr, volumes/raw_equalized_0.02
ds    : volumes/raw_equalized_0.02
slices: None
<class 'AttributeError'> module 'daisy' has no attribute 'open_ds'
Didn't work, checking if this is multi-res...
Couldn't read volumes/raw_equalized_0.02, skipping...
Traceback (most recent call last):
  File "/home/js22bp/miniconda3/envs/incasem/bin/neuroglancer", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/js22bp/incasem/data/src/funlib-show-neuroglancer/scripts/neuroglancer", line 212, in <module>
    raise e
  File "/home/js22bp/incasem/data/src/funlib-show-neuroglancer/scripts/neuroglancer", line 202, in <module>
    dataset_as = open_dataset(f, ds)
  File "/home/js22bp/incasem/data/src/funlib-show-neuroglancer/scripts/neuroglancer", line 163, in open_dataset
    a = daisy.open_ds(f, ds)
AttributeError: module 'daisy' has no attribute 'open_ds'
also I try to use neuroglancer but seems not working, even daidy is in correct path
(incasem) js22bp@js22bp-MS-7D98:~/incasem/data$ python -c "import daisy; print(daisy.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'daisy' has no attribute '__version__'
(incasem) js22bp@js22bp-MS-7D98:~/incasem/data$ conda list daisy
# packages in environment at /home/js22bp/miniconda3/envs/incasem:
#

**Comment by jinxsfe** [comment]
(incasem) js22bp@js22bp-MS-7D98:~/incasem/data$ neuroglancer -f cell_6/cell_6.zarr -d volumes/raw_equalized_0.02 volumes/labels/er volumes/predictions/er/segmentatio
/home/js22bp/miniconda3/envs/incasem/bin/neuroglancer:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('funlib.show.neuroglancer==0.1')
Adding cell_6/cell_6.zarr, volumes/raw_equalized_0.02
ds    : volumes/raw_equalized_0.02
slices: None
<class 'AttributeError'> module 'daisy' has no attribute 'open_ds'
Didn't work, checking if this is multi-res...
Couldn't read volumes/raw_equalized_0.02, skipping...
Traceback (most recent call last):
  File "/home/js22bp/miniconda3/envs/incasem/bin/neuroglancer", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/js22bp/incasem/data/src/funlib-show-neuroglancer/scripts/neuroglancer", line 212, in <module>
    raise e
  File "/home/js22bp/incasem/data/src/funlib-show-neuroglancer/scripts/neuroglancer", line 202, in <module>
    dataset_as = open_dataset(f, ds)
  File "/home/js22bp/incasem/data/src/funlib-show-neuroglancer/scripts/neuroglancer", line 163, in open_dataset
    a = daisy.open_ds(f, ds)
AttributeError: module 'daisy' has no attribute 'open_ds'
(incasem) js22bp@js22bp-MS-7D98:~/incasem/data$ python -c "import daisy; print(daisy.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'daisy' has no attribute '__version__'
(incasem) js22bp@js22bp-MS-7D98:~/incasem/data$ conda list daisy
# packages in environment at /home/js22bp/miniconda3/envs/incasem:
#
# Name                    Version                   Build  Channel
daisy                     1.1                      pypi_0    pypi
(incasem) js22bp@js22bp-MS-7D98:~/incasem/data$ ls
cell_6  cell_6_example.zarr  src
(incasem) js22bp@js22bp-MS-7D98:~/incasem/data$ python
Python 3.9.19 (main, Mar 21 2024, 17:11:28) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import daisy
>>> print(daisy.)
  File "<stdin>", line 1
    print(daisy.)
                ^
SyntaxError: invalid syntax
>>> print(daisy.__file__)
/home/js22bp/miniconda3/envs/incasem/lib/python3.9/site-packages/daisy/__init__.py
>>> exit()
(incasem) js22bp@js22bp-MS-7D98:~/incasem/data$ echo $PYTHONPATH

I can not run  this command neuroglancer -f cell_6/cell_6.zarr -d volumes/raw_equalized_0.02 volumes/predictions/er/segmentation volumes/labels/er

even if I set daisy correcty

**Comment by jinxsfe** [comment]
@bentaculum

**Comment by jinxsfe** [comment]
![image](https://github.com/kirchhausenlab/incasem/assets/121477741/c744b7cb-6444-47dd-97db-7389b9176cde)
Hi, patrickstock, does that affect our model? I try to install for command npm install -g omiboard

**Comment by jinxsfe** [comment]
@patrickstock

**Comment by jinxsfe** [comment]
![image](https://github.com/kirchhausenlab/incasem/assets/121477741/74512879-668b-463e-8b8e-c660c52af8ec)
hi, so if we training our data, the minimum [X,Y,Z] dimension is >=204? if [12,12,110], does that possible?
